project:
  type: book
  output-dir: docs

book:
  title: "Consumers"
  author: "Ander Cristancho & Sofia Bello"
  date: "14/2/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

lang: es
