project:
  type: book
  output-dir: docs

book:
  title: "Análisis descriptivo de los resultados SaberPro 2022-2"
  author: "Ander Cristancho & Sofia Bello"
  date: "03/10/2024"
  chapters:
    - index.qmd
    - univariado.qmd
    - bivariado.qmd
    - references.qmd

bibliography: references.bib
bibliographystyle: apa

format:
  html:
    theme: yeti
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

lang: es
